# Generated by Django 6.0.4 on 2026-04-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("vendor", "Vendor"),
                            ("organization", "Organization"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("authority_score", models.FloatField(default=0.5)),
                ("website_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("bluesky_handle", models.CharField(blank=True, max_length=255)),
                ("mastodon_handle", models.CharField(blank=True, max_length=255)),
                ("twitter_handle", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=512)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("source_plugin", models.CharField(max_length=64)),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("published_date", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("content_text", models.TextField()),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("topic_description", models.TextField()),
                ("content_retention_days", models.PositiveIntegerField(default=365)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "low_confidence_classification",
                                "Low Confidence Classification",
                            ),
                            ("borderline_relevance", "Borderline Relevance"),
                        ],
                        max_length=64,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("human_approved", "Human Approved"),
                            ("human_rejected", "Human Rejected"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_queue_items",
                        to="core.content",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_queue_items",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["resolved", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upvote_authority_weight", models.FloatField(default=0.1)),
                ("downvote_authority_weight", models.FloatField(default=-0.05)),
                ("authority_decay_rate", models.FloatField(default=0.95)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant config",
                "verbose_name_plural": "Tenant configs",
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.content",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=64)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_results",
                        to="core.content",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="core.skillresult",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_results",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content", "skill_name"],
                        name="core_skillr_content_0d49f9_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="core_skillr_tenant__1bde27_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_name", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("items_fetched", models.IntegerField(default=0)),
                ("items_ingested", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "plugin_name", "-started_at"],
                        name="core_ingest_tenant__874035_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="core_entity_unique_tenant_name"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["tenant", "-published_date"],
                name="core_conten_tenant__01494c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["tenant", "-relevance_score"],
                name="core_conten_tenant__a1c995_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["url"], name="core_conten_url_4d8416_idx"),
        ),
        migrations.AddConstraint(
            model_name="userfeedback",
            constraint=models.UniqueConstraint(
                fields=("content", "user"), name="core_feedback_unique_content_user"
            ),
        ),
    ]
