# Generated by Django 6.0.4 on 2026-04-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_newsletter_intake"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="newsletterintake",
            new_name="core_newsle_project_eee7a4_idx",
            old_name="core_newsle_project_2c63fb_idx",
        ),
        migrations.AlterField(
            model_name="sourceconfig",
            name="plugin_name",
            field=models.CharField(
                choices=[("rss", "RSS"), ("reddit", "Reddit"), ("bluesky", "Bluesky")],
                max_length=64,
            ),
        ),
    ]
