# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sourceconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="embedding_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="content",
            name="is_reference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["tenant", "is_reference"], name="core_conten_tenant__e80c35_idx"),
        ),
    ]