# Generated by Django 6.0.4 on 2026-04-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_rename_core_newsle_project_2c63fb_idx_core_newsle_project_eee7a4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueskyCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=255)),
                ("app_password_encrypted", models.TextField(blank=True)),
                ("pds_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bluesky_credentials",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bluesky credentials",
                "ordering": ["project__name"],
            },
        ),
    ]
